### ISSUE TITLE
Introduce more typesafety for Block definitions

### ISSUE THREAD

**Issue by pmalacho-mit** [mitmedialab/prg-extension-boilerplate#140]
There are two key places that the definition of a [Block type](https://github.com/mitmedialab/prg-extension-boilerplate/blob/parker-TypescriptConcept/packages/scratch-vm/src/typescript-support/types.ts#L36) can be made more typesafe, leading to a better developer experience:

1. Restrict the `type` of Blocks based on the return type of it's associated operation (i.e. if a Block is of type `Block<() => void>` it should have a `type` field of `BlockType.Command`, and if it is a `Block<() => number>` (or any non-void return type) it should have a `type` field of `BlockType.Reporter`)
2. Restrict the `type` of an [Argument<T>](https://github.com/mitmedialab/prg-extension-boilerplate/blob/parker-TypescriptConcept/packages/scratch-vm/src/typescript-support/types.ts#L22) based on it's generic paramter (i.e. if something is an Argument<number>, then `type` field should be limited to take on the value of `ArgumentType.Number`) NOTE: Some thought might be necessary to handle the less traditional argument types (I'm not even sure what all of the different argument types look like in terms of javascript types)

**Comment by DolevArtzi** [comment]
for **(1)**, if a return type of `void` indicates `Command` and a non-void return type indicates `Reporter`, how could you have a block where the `BlockType` is neither `Command` nor `Reporter`?

**Comment by DolevArtzi** [comment]
Ideally, if we could constrain a block such that it can only be a `BlockType.Boolean` if the function returns `boolean`, however https://github.com/mitmedialab/prg-extension-boilerplate/blob/c354423d38213078beb0f0d02c3391529489638f/packages/scratch-vm/src/extensions/scratch3_ev3/index.js#L1244, for example, is a `BlockType.BOOLEAN` but it returns `boolean | undefined` (although this is the only such example I could find that doesn't definitely return `boolean`). Perhaps we could constrain it to be something that returns `boolean | undefined | null`?

**Comment by pmalacho-mit** [comment]
I think we should actually restrict it to `boolean` -- thats what the documentation describes:
```
                    //   BlockType.BOOLEAN - same as REPORTER but returns a Boolean value
```
from https://github.com/LLK/scratch-vm/blob/develop/docs/extensions.md

**Comment by DolevArtzi** [comment]
according to [this source](https://ocular.jeffalo.net/topic/277217) *'//This can either be Boolean, reporter, command, or hat'* and [this source](https://medium.com/@hiroyuki.osaki/scratch-3-block-types-you-can-develop-and-samples-191b0d769b91) *'You can use four fundamental block types. COMMAND, REPORTER, BOOLEAN, HAT.'*- we need to worry about `COMMAND`, `REPORTER`, `BOOLEAN` and `HAT`. Still looking into how to deal with `HAT` at the moment.

**Comment by DolevArtzi** [comment]
https://github.com/mitmedialab/prg-extension-boilerplate/pull/151
