### ISSUE TITLE
Handle casting of less common argument types

### ISSUE THREAD

**Issue by pmalacho-mit** [mitmedialab/prg-extension-boilerplate#142]
Something I didn't really consider when originally implementing the typescript framework is how to handle casting the less common argument types (like matrix) -- frankly, I never really even worked with them. 

We need to handle all possible argument types here: https://github.com/mitmedialab/prg-extension-boilerplate/blob/parker-TypescriptConcept/packages/scratch-vm/src/typescript-support/Extension.ts#L100

**Comment by DolevArtzi** [comment]
- **Angle**
- **Boolean**
    - `boolean`
- **Color**
    - <img width="174" alt="Screen Shot 2022-08-03 at 9 15 00 AM" src="https://user-images.githubusercontent.com/85849407/182616890-c535a9b1-f3db-4bef-afec-734ca03f5f78.png">
    -  the pen extension also uses the following enum: `const ColorParam = {
    COLOR: 'color',
    SATURATION: 'saturation',
    BRIGHTNESS: 'brightness',
    TRANSPARENCY: 'transparency'
    };`
    - used heavily by `scratch3_pen` extension
    - `Cast.toRgbColorObject` used on param of type `ArgumentType.Color`
    - `Color` class defined here: https://github.com/mitmedialab/prg-extension-boilerplate/blob/develop/packages/scratch-vm/src/util/color.js 
- **Number**
    - `number` 
- **String**
    - `string` 
- **Matrix**
- **Note**
- **Image**

**Comment by DolevArtzi** [comment]
https://github.com/mitmedialab/prg-extension-boilerplate/commit/cc99c60a590a29769d4984bae568bc56f262a9b2 handles all but `ArgumentType.Image`.
