### ISSUE TITLE
Remove keys from code repo

### ISSUE THREAD

**Issue by randi-c-dubs** [mitmedialab/prg-extension-boilerplate#155]
GDrive secrets are exposed in code (menu-bar.jsx on raica and google-drive-save branches).

**Comment by randi-c-dubs** [comment]
From pmalacho-mit: we can do API secrets somewhat like this: https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/GitHub-Actions-Secrets-Example-Token-Tutorial

**Comment by pmalacho-mit** [comment]
Opted to use gdrive api restrictions: https://cloud.google.com/api-keys/docs/add-restrictions-api-keys
