### ISSUE TITLE
On cloneing the repo. and in scratch-gui there is no option for save and save as new option ?

### ISSUE THREAD

**Issue by saxenapritesh** [mitmedialab/prg-extension-boilerplate#172]
On cloneing the repo. and in scratch-gui there is no option for save and save as new option ?

![Screenshot from 2022-10-07 14-57-12](https://user-images.githubusercontent.com/26432256/194521461-5451a61b-dc68-4951-a4db-f378757ace2f.png)

**( Here i want that save new and save as a copy  function code )**

I have checked the code there is a condition for usersession and username in (packages/scratch-gui/src/components/menu-bar/menu-bar.jsx )

It called `handleClickSave` function on clicking and inside that function it called two functions.

**handleClickSave () {
        this.props.onClickSave();
        this.props.onRequestCloseFile();
}**

It called `dispatch(manualUpdateProject())` in ( packages/scratch-gui/src/components/menu-bar/save-status.jsx )

In that it just enables the loader there is nothing like to save that project anywhere.

Is there any way to check the save off that project code in if it is another repo. then please share it and if it is the same repo. please share the path of file and function to save that file.

**Comment by pmalacho-mit** [comment]
Hi @saxenapritesh !

Unfortunately this repo is completely separate from the official Scratch platform, so we don't/can't make use of Scratch's user accounts and the functionality associated with them (like saving to the cloud). In other words, as is you can only save/load to a user's computer.

We do know from the teachers we work with that being able to save / load projects from the cloud is very important to them, so we are working on supporting the major cloud storage platforms (Google Drive, Dropbox, etc.), but each of those requires their own development effort. I'd expect us to support Google Driving saving/loading by the end of the year. Do you have any input on which platform you'd like us to support after that?

Also, would you like to let me know your use-case and I can make my best recommendation on how to handle it with what's available in this repo currently?
