### ISSUE TITLE
Supporting loading "recipes"

### ISSUE THREAD

**Issue by pmalacho-mit** [mitmedialab/prg-extension-boilerplate#196]
What goes into a recipe?

- Default extension(s)
- ? Project to load
- Tutorials?
- (maybe) code to run on load

**Comment by randi-c-dubs** [comment]
Default extensions, default projects, and tutorials can be specified through URL encoding
https://playground.raise.mit.edu/main/?tutorial=<tutorial name>?project=<link to .sb3 file>

I think this is the easiest and most flexible way to go about it.

**Comment by pmalacho-mit** [comment]
Great point, @randi-c-dubs! Will try it out and add some documentation sometime this week.

I think we might as well do that, and if we get any feedback that the URLs it makes are too long or anything like that, then and only then will we take on this new development.
