### ISSUE TITLE
Jimmy's Notes

### ISSUE THREAD

**Issue by pmalacho-mit** [mitmedialab/prg-extension-boilerplate#215]

**Comment by magicshadow797** [comment]
Not very clear about what the block types (with options, block that lets you type your own string, etc.) are that I can use or where to find them.
What is the "util" parameter in the operation part of the block functionality class?
Unclear about how to upload my extension to the localhost version of PRG, getting error:
<img width="569" alt="Screen Shot 2023-01-10 at 6 45 39 PM" src="https://user-images.githubusercontent.com/117794650/211706275-4907412b-560c-4d07-b098-f6d5d450e496.png">

**Comment by magicshadow797** [comment]
opcode -> name of block within js file when the block is defined, but this is also the name of the function within the js file that the prg block runs when it is used
_loop() -> runs until a resolve callback is returned or a reject callback is returned. Extension program code will not continue until _loop() has finished. Is its purpose to get an estimate of the hand's position and also give the computer time to estimate the hand's position? Is estimateThrottleTimeout the max time the program can take to find the hand position before restatrting or is it the amount of time between reestimating the hand's position?

Why are the reset(), scan(), and connect() functions empty?

What does async mean? 
- async fxn returns a Promise
- async fxns can run at the same time as the rest of the code?
-What is a Promise?
   - (???) Promise is an (object?) that some other part of the code needs before it can run 
- More info: https://blog.logrocket.com/async-await-in-typescript/

What is runtime?
- "the time that a program is running alongside all the external instructions needed for proper execution"
- More info: https://www.techtarget.com/searchsoftwarequality/definition/runtime

**Comment by pmalacho-mit** [comment]
Opcode: Yep, I think you have it exactly right! It might be a little confusing, but blocks don't necessarily have a 'name' -- so with that said, their `opcode` can be thought of as their name, since that indicates the function that is called when the block is executed and in that since is what really defines the behavior of the block. That's why in the framework, I decided to put the function tied to a block (in the framework, it's called the `operation`) directly in its definition.

_loop: definitely notice the `while (true)` at the top of this function, so it will loop for the length of the program (as this function is called in the extension's constructor). So I think the purpose is, for each loop:

1.  Retrieve the current video frame
2. Have the model estimate the hand position's on the current frame (an async process) 
3. Once the frame is process, indicate whether the handpose was successfully found using the "Peripheral Connection" status (I believe this is purely for visual indication, nothing more)
4. Perform another async call to wait for some amount of time before going to the next iteration of the loop -- this must just be to try to avoid doing the frame processing constantly (as this would slow down the entire program -- javascript is single-threaded by nature, so any javascript you execute also slows down the UI reactivity). We can play with this 'throttling' mechanism later to make sure it make sense. The whole `/ 4` thing looks a little arbitrary to me, so we can investigate later, but no need to worry about it much initially. 

reset / scan / connect: Not sure, but did you check if they were present in the `scratch3_video_sensing/index.js`? That's that official scratch extension I mentioned yesterday which I assume is what the poseHand developers just copy and pasted. I bet those functions come from that file originally, and they just got left in. Silly developers!

async: Nice research! Here's a good video too: https://youtu.be/8aGhZQkoFbQ <-- that kind of makes it clear that the async function just queues up code to run later, and javascript's 'event loop' manages when that code is called.

runtime: Unfortunately, the runtime referenced in the code refers to a Scratch specific concept. The runtime (implemented in `packages/scratch-vm/src/engine/runtime.js` -- warning! it's long). You can see this mentioned here: https://github.com/LLK/scratch-vm/blob/develop/docs/extensions.md#defining-an-extension For our purposes, you can just thing of the `runtime` as something that extensions are given when they are constructed, and it helps interact with the Scratch environment, like accessing the video feed.

**Comment by magicshadow797** [comment]
I was thinking that maybe the video toggle and video transparency blocks for the hand posing, body posing, face posing, and video sensing extensions could somehow be grouped together into one file and import this file into the three different extensions. This way, code would be less repetitive and anyone making a video extension in the future could just import this file to simplify their process. I know I mentioned this earlier to you but this is just me writing it down!

**Comment by magicshadow797** [comment]
TO GET ALL UPDATES FROM GITHUB:

git checkout <your branch> #if you aren't already there
git pull # download all the latest changes to the origin versions of all branches
# remember, there's your local version of a branch, and then there's the 'origin' version stored on the server
git merge origin/dev # merge the dev branch into the current branch you're on so you get all of the changes that were brought to dev via my pull request

**Comment by magicshadow797** [comment]
LOCATION OF ORIGINAL SCRATCH EXTENSIONS:
prg-extension-boilerplate/packages/scratch-vm/src/extensions

**Comment by magicshadow797** [comment]
`.PERIPHERAL_CONNECTED` and `.PERIPHERAL_DISCONNECTED` -- What are they?
Do I need to do `launchPeripheralConnectionFlow: true;`?

What is the init() function actually for if we can just use a constructor instead? What should go in init() and what should go in the constructor? Is the constructor only for accessing runtime?

Where can I find out info about the setXY() function?
Where can I find more info about `handPoseState`?

**Comment by pmalacho-mit** [comment]
Great questions Jimmy! I'll tackle one by one. 

- The usage of `.PERIPHERAL_CONNECTED` and `.PERIPHERAL_DISCONNECTED` (and specifically emitting those events through the runtime) seem to be this extension author's attempt to show to the user that the model is both (1) loaded and (2) predicting hand poses. To me, this just seems like a 'hack' to utilize some UI for not necessarily it's intended purpose, so it's just being a little clever! Those events control whether there's a little check mark (indicating `PERIPHERAL_CONNECTED`) or an exclamation point (indicating `PERIPHERAL_DISCONNECTED`) next to the extension name 
<img width="237" alt="Screen Shot 2023-01-18 at 11 58 21 AM" src="https://user-images.githubusercontent.com/95306112/213246182-c950d43e-4b4b-4247-b26b-5e91c7cf8610.png">

- No need to use `launchPeripheralConnectionFlow: true;` -- you'd only consider doing so if that was specified in the old extensions `getInfo` method, but I don't believe it is

- So you should use `init` INSTEAD OF the constructor. I tried to build this into the framework, but you're right that you were still allowed to define the constructor in your extension class. I just pushed some changes to `dev` to hopefully further prevent developers from implementing their own constructor method, but I'll need to document that too. But just to answer your constructor -- use init as if it were a constructor. The reason for all this is that I want to be able to control the construction of extensions, and thus I don't want people writing custom constructors. 

- packages/scratch-vm/src/sprites/rendered-target.js -- line 267
- https://github.com/tensorflow/tfjs-models/tree/master/handpose and https://drive.google.com/file/d/1sv4sSb9BSNVZhLzxXJ0jBv9DqD-4jnAz/view (the output of the model is what gets stuffed into `handPoseState`) -- so you can try `console.log`ing `handPoseState` and hopefully using those references to figure out what all the keyvalue pairs are
-
