### ISSUE TITLE
Failed to execute 'importScripts' on 'WorkerGlobalScope'

### ISSUE THREAD

**Issue by ttseng** [mitmedialab/prg-extension-boilerplate#34]
Thanks for making this helpful repo!  

I made a copy of the repo using the Gitpod link, and then followed [the instructions](https://github.com/mitmedialab/prg-extension-boilerplate#adding-a-new-scratch-extension) to build my own Scratch extension.  Currently, I just copied an existing extension into `packages/scratch-vm/src/extensions/plushpal/index.js` 

When I try to load the new blocks, I'm able to view the extensions from the list, but when I click the extension, it silently fails and I see the following error in the console:

`Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://...gitpod.io/plushpal' failed to load.`

Do you have any ideas why this might be?  Here's a link to the repo: 
https://gitpod.io/#snapshot/f0163321-ad97-4b94-88cf-b66124ad4f48

**Comment by randi-c-dubs** [comment]
Sorry ttseng, this repo is like a side-side project of busy grad students and I noticed the issue quite late. If you still have this problem/if anyone else does here's what I believe happens:
1. You probably added things to package.json, most likely the scratch-gui package.json using npm install
2. Doing this added the new packages to your package.json dependencies and also changed which scratch-vm it's pointing to
If that sounds about right, then all you need to do is go and link your local scratch-vm again. The easiest way to do that is to run
npx lerna bootstrap --force-local

**Comment by randi-c-dubs** [comment]
p.s. PlushPal is so cool!
