### ISSUE TITLE
Generate 'play note' Scratch blocks for sequences of notes

### ISSUE THREAD

**Issue by DolevArtzi** [mitmedialab/prg-extension-boilerplate#89]
Currently, we have `generate new music` and `complete music with _ steps and _ temperature`. This proposed change would leave `complete music with _ steps and _ temperature` mostly unchanged, but increase the options that the user has to generate new music. This would involve two new blocks: 
   * `play generated music on [INSTRUMENT_NAME]` **(1)**
        - will behave like `generate new music`
        - could potentially not include instrument as argument, making it the same as `generate new music` assuming that  
   (https://github.com/mitmedialab/prg-extension-boilerplate/issues/88) is resolved
   * `generate notes for [INSTRUMENT_NAME]` **(2)**
        - generates a chunk of Scratch blocks that go into the user's workspace that they can execute at will
             - two major benefits of this are (1) you can play the same generated sequence multiple times, (2) you can easily pull individual notes out (mix and match) from a generated note sequence
        - for example, you might generate something that looks like this (though probably longer and with fancier notes than just '60'):  
![Screen Shot 2022-05-19 at 5 22 03 PM](https://user-images.githubusercontent.com/85849407/169406741-7db397a1-8d46-421b-84f3-a4c3a52cefeb.png)

**Comment by pmalacho-mit** [comment]
After discussing with @DolevArtzi , we have a proposal for how to implement this:

- Create a `_playNotes(...)` function similar to the existing internal `_playNote(...)` function that makes use of the `player.once('stop', ...)` mechanism to trigger the _next_ sound to play when one finishes. **NOTE:** things might get a little tricky with playing more than one sound at once, as you might need to make multiple input nodes, but let's cross the bridge when we come to it (will require digging a little bit into the [AudioContext](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext) api)
- Create a `playNotes(...)` function (similar to the existing `playNote(...)` that instead accepts a sequence of notes) that, when `util.stackTimerNeedsInit()` is true makes use of the `_playNotes(...)` function to cue up all the notes to play. Separately, it should calculate the total time of the note sequence, and use the `util.startStackTimer(...)` function to set the stack timer to the appropriate duration

**Comment by DolevArtzi** [comment]
https://github.com/mitmedialab/prg-extension-boilerplate/pull/96
